In [1]:
import sys;sys.path.append('..')
import pandas as pd,numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('../data/retail_campaign.csv')
df.head()

,customer_id,recency,history,used_discount,used_bogo,is_referral,zip_code_Rural,zip_code_Surburban,zip_code_Urban,channel_Multichannel,channel_Phone,channel_Web,discount,revenue
0,2,6,329.08,1,1,1,1,0,0,0,0,1,0,0.0
1,4,9,675.83,1,0,1,1,0,0,0,0,1,1,0.0
2,9,9,675.07,1,1,1,1,0,0,0,1,0,1,0.0
3,14,2,101.64,0,1,0,0,0,1,0,0,1,1,25.0
4,15,4,241.42,0,1,1,1,0,0,1,0,0,0,0.0

In [4]:
from src.casual_graph import build_model,identify_and_estimate
from src.refutation import run_dowhy_refuters
model=build_model(df.sample(min(len(df),20000),random_state=0))
identified,estimate=identify_and_estimate(model)
run_dowhy_refuters(model,identified,estimate,sims=20)

                  test            expected  original_effect  new_effect
0    Placebo treatment  effect drops to ~0         1.883255   -0.046139
1  Random common cause  estimate unchanged         1.883255    1.883268
2          Data subset     estimate stable         1.883255    1.883439

In [6]:
from src.refutation import manual_refuters
from src.double_ml import ate_linear_dml
sample=df.sample(min(len(df),20000),random_state=0)
manual_refuters(sample,ate_linear_dml)

c:\Users\DELL\Desktop\Python Course\venv\Lib\site-packages\econml\sklearn_extensions\linear_model.py:1946: UserWarning: Co-variance matrix is underdetermined. Inference will be invalid!
  warnings.warn("Co-variance matrix is underdetermined. Inference will be invalid!")
c:\Users\DELL\Desktop\Python Course\venv\Lib\site-packages\econml\sklearn_extensions\linear_model.py:1946: UserWarning: Co-variance matrix is underdetermined. Inference will be invalid!
  warnings.warn("Co-variance matrix is underdetermined. Inference will be invalid!")
c:\Users\DELL\Desktop\Python Course\venv\Lib\site-packages\econml\sklearn_extensions\linear_model.py:1946: UserWarning: Co-variance matrix is underdetermined. Inference will be invalid!
  warnings.warn("Co-variance matrix is underdetermined. Inference will be invalid!")
c:\Users\DELL\Desktop\Python Course\venv\Lib\site-packages\econml\sklearn_extensions\linear_model.py:1946: UserWarning: Co-variance matrix is underdetermined. Inference will be invalid!
  warnings.warn("Co-variance matrix is underdetermined. Inference will be invalid!")
c:\Users\DELL\Desktop\Python Course\venv\Lib\site-packages\econml\sklearn_extensions\linear_model.py:1946: UserWarning: Co-variance matrix is underdetermined. Inference will be invalid!
  warnings.warn("Co-variance matrix is underdetermined. Inference will be invalid!")
c:\Users\DELL\Desktop\Python Course\venv\Lib\site-packages\econml\sklearn_extensions\linear_model.py:1946: UserWarning: Co-variance matrix is underdetermined. Inference will be invalid!
  warnings.warn("Co-variance matrix is underdetermined. Inference will be invalid!")
c:\Users\DELL\Desktop\Python Course\venv\Lib\site-packages\econml\sklearn_extensions\linear_model.py:1946: UserWarning: Co-variance matrix is underdetermined. Inference will be invalid!
  warnings.warn("Co-variance matrix is underdetermined. Inference will be invalid!")
c:\Users\DELL\Desktop\Python Course\venv\Lib\site-packages\econml\sklearn_extensions\linear_model.py:1946: UserWarning: Co-variance matrix is underdetermined. Inference will be invalid!
  warnings.warn("Co-variance matrix is underdetermined. Inference will be invalid!")
c:\Users\DELL\Desktop\Python Course\venv\Lib\site-packages\econml\sklearn_extensions\linear_model.py:1946: UserWarning: Co-variance matrix is underdetermined. Inference will be invalid!
  warnings.warn("Co-variance matrix is underdetermined. Inference will be invalid!")
c:\Users\DELL\Desktop\Python Course\venv\Lib\site-packages\econml\sklearn_extensions\linear_model.py:1946: UserWarning: Co-variance matrix is underdetermined. Inference will be invalid!
  warnings.warn("Co-variance matrix is underdetermined. Inference will be invalid!")
c:\Users\DELL\Desktop\Python Course\venv\Lib\site-packages\econml\sklearn_extensions\linear_model.py:1946: UserWarning: Co-variance matrix is underdetermined. Inference will be invalid!
  warnings.warn("Co-variance matrix is underdetermined. Inference will be invalid!")
c:\Users\DELL\Desktop\Python Course\venv\Lib\site-packages\econml\sklearn_extensions\linear_model.py:1946: UserWarning: Co-variance matrix is underdetermined. Inference will be invalid!
  warnings.warn("Co-variance matrix is underdetermined. Inference will be invalid!")

,test,expected,original_effect,new_effect,spread,passed
0,Placebo treatment,"placebo effects ~0, real effect stands out",1.873127,-0.013550,0.110441,True
1,Random common cause,estimate unchanged,1.873127,1.890536,NaN,True
2,Data subset (70%),estimate stable,1.873127,1.893375,0.081695,True